[EPIC] Parse args, correct frames order
codex-team/hawk.php pull request #30
Opened 2021-06-04 19:46 UTC by talyguryn

**was** and **now**

![image](https://user-images.githubusercontent.com/15259299/120855076-adf90600-c586-11eb-83cc-95e5c657efd7.png)

2021-06-10 05:22 UTC, neSpecc requested changes

2021-06-10 05:22 UTC, neSpecc commented on src/Util/Stacktrace.php
>          ];
can we also get a column number?

2021-06-10 05:22 UTC, neSpecc commented on src/Util/Stacktrace.php
> +        $newStack[$i] = [
I see same [lines](https://github.com/codex-team/hawk.php/pull/30/files#diff-74543a71ba049e8ca882af5cb1bcfe0fdf14071f481d062e8cff49bdcfda1321R119-R123) below. Maybe we can remove duplication

2021-06-10 05:22 UTC, neSpecc commented on src/Util/Stacktrace.php
> +             * Fill function and arguments data for the previous frame
why previous? describe in comments

2021-06-10 05:22 UTC, neSpecc commented on src/Util/Stacktrace.php
> +     * @param $frame
no type, no description

2021-06-10 05:22 UTC, neSpecc commented on src/Util/Stacktrace.php
> +    private static function composeFunctionName($frame)
specify return and param types

2021-06-10 05:22 UTC, neSpecc commented on src/Util/Stacktrace.php
> +     * Compose function name with a class
What does it mean "with a class"? Add an example

2021-06-10 05:22 UTC, neSpecc commented on src/Util/Stacktrace.php
> +            if (isset($frame['class'])) {
maybe `!empty()` ?

2021-06-10 05:22 UTC, neSpecc commented on src/Util/Stacktrace.php
> +        } catch (\Exception $e) {
describe this case

2021-06-10 05:22 UTC, neSpecc commented on src/Util/Stacktrace.php
> +    private static function getArgs($frame)
add param and return types

2021-06-10 05:22 UTC, neSpecc commented on src/Util/Stacktrace.php
> +    private static function getReflectionMethod($frame)
specify types

2021-06-10 05:22 UTC, neSpecc commented on src/Util/Stacktrace.php
> +            foreach ($frame['args'] as $index => $value) {
unsafe calling `$frame['args']`. Is it always specified?

2021-06-11 17:50 UTC, talyguryn commented on src/Util/Stacktrace.php
>          ];
no. php exception does not contain this info

2021-06-11 18:19 UTC, talyguryn commented on src/Util/Stacktrace.php
> +    private static function getReflectionMethod($frame)
as i know, we can not use multiple types for a function return for php <8

2021-06-11 18:32 UTC, talyguryn commented on src/Util/Stacktrace.php
> +            foreach ($frame['args'] as $index => $value) {
yep. but i'll add a check above

2021-06-11 18:32 UTC, talyguryn commented on src/Util/Stacktrace.php
> +             * Fill function and arguments data for the previous frame
done

2021-06-11 18:33 UTC, talyguryn commented on src/Util/Stacktrace.php
> +        $newStack[$i] = [
done

2021-06-15 19:43 UTC, neSpecc commented on src/Util/Stacktrace.php
> +        $newStack[$i] = [
it is not done

2021-06-15 20:26 UTC, talyguryn commented on src/Util/Stacktrace.php
> +        $newStack[$i] = [
oh, i see. it doesn't matter. this part always will be, but that part is in a cycle. this is the simplest solution

2021-06-15 20:43 UTC, khaydarov commented on src/Util/Stacktrace.php
> +    private static function composeFunctionName($frame): string
```suggestion
    private static function composeFunctionName(array $frame): string
```

2021-06-15 20:43 UTC, khaydarov commented on src/Util/Stacktrace.php
> +    private static function getArgs($frame): array
```suggestion
    private static function getArgs(array $frame): array
```

2021-06-15 20:43 UTC, khaydarov commented on src/Util/Stacktrace.php
> +    private static function getReflectionMethod($frame)
```suggestion
    private static function getReflectionMethod(array $frame): ?ReflectionFunctionAbstract
```

2021-06-16 09:07 UTC, khaydarov approved these changes

2021-06-16 09:07 UTC, khaydarov commented on src/Util/Stacktrace.php
> +        var_dump($stack);
dont forget to remove pls

2021-06-16 09:09 UTC, neSpecc approved these changes

2021-06-16 09:18 UTC, merged