Add unit tests and fix fields casting on arguments
codex-team/hawk.php pull request #33
Opened 2021-07-02 16:23 UTC by khaydarov

2021-07-05 20:52 UTC, neSpecc commented on src/Util/Stacktrace.php
> +        } else {
what about strings, numbers, iterables?

2021-07-22 12:12 UTC, khaydarov commented on src/Util/Stacktrace.php
> +        } else {
string will be as string, numbers will be casted to string as default behaviour and iterables will be converted to array and then to string

2021-07-22 12:42 UTC, neSpecc requested changes

2021-07-22 12:42 UTC, neSpecc commented on tests/Unit/Addons/HeadersTest.php
> +        $result = $headers->resolve();
1. Headers should contain all given HTTP Headers, not predefined server variables
2. Headers should be tested with an Integration test. Unit test should be removed

2021-07-22 12:42 UTC, neSpecc commented on tests/Unit/Addons/OsTest.php
> +class OsTest extends TestCase
Let's remove OS integration with its test because it is unuseful information

2021-07-22 12:42 UTC, neSpecc commented on tests/Unit/Addons/RuntimeTest.php
> +class RuntimeTest extends TestCase
Lets remove Runtime integration with its test, because it is unuseful information

2021-07-22 12:42 UTC, neSpecc commented on tests/Unit/EventPayloadFactoryTest.php
> +    public function testCreationWithCustomStacktrace(): void
```suggestion
    public function testCreationWithCustomException(): void
```

2021-07-22 13:05 UTC, neSpecc commented on src/Addons/Headers.php
> +                    $key = str_replace(
That should be covered by Unit Tests

2021-07-22 13:50 UTC, neSpecc approved these changes

2021-07-22 14:50 UTC, khaydarov commented on src/Addons/Headers.php
> +                    $key = str_replace(
it is polyfill to standard getallheaders method, dont think it make sense

2021-07-22 15:45 UTC, talyguryn approved these changes

2021-08-05 12:12 UTC, merged